apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.kompose.yml -o k8s/ --controller deployment
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: svc-backend
  name: svc-backend
spec:
  ports:
    - name: "8002"
      port: 80
      targetPort: 8002
  selector:
    io.kompose.service: svc-backend
  type: LoadBalancer
status:
  loadBalancer: {}
